# Allow Thymeleaf templates to be reloaded at dev time
spring:
  thymeleaf:
    cache: false
  resources:
    chain:
      enabled: true     
server:
  port: 8080
  #context-path: /client
  tomcat:
    accesslog:
      enabled: true
      basedir: target/tomcat
#Database
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/networking
  username: root
  password: root
#Hibernate
hibernate:
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         show_sql: true
         format_sql: true
         hbm2ddl:
               auto: update
entitymanager:
            packagesToScan: org.networking
            
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG

